data:
  tokenizer: null
  task_suite_name: libero_10
  num_trials_per_task: 50
  data_dir: null
  filter_warmup: False
  prompt_key: prompt
  system_prompt: null
  max_prompt_length: 512
  max_response_length: 512
  train_batch_size: 1024
  val_batch_size: 1312
  return_raw_input_ids: False  # This should be set to true when the tokenizer between policy and rm differs
  return_raw_chat: False
  n_samples: 1
  filter_accuracy: False
  filter_truncated: False
  accuracy_lower_bound: 0.0
  accuracy_upper_bound: 1.0
  oversample_factor: 1.0 # Sample more responses than the batch size
  filter_format: True
  zero: False
  sample_num: -1

actor_rollout_ref:
  hybrid_engine: True
  model:
    vla: openvla-oft
    action_token_len: 7
    action_chunks_len: 8
    resume: False
    path: ~/models/deepseek-llm-7b-chat
    external_lib: null
    override_config: { }
    enable_gradient_checkpointing: False
    use_remove_padding: False
    lora_rank: 0  # Set to positive value to enable LoRA (e.g., 32)
    lora_alpha: 32  # LoRA scaling factor
    target_modules: all-linear  
  actor:
    vla: ${actor_rollout_ref.model.vla}
    action_token_len: ${actor_rollout_ref.model.action_token_len}
    action_chunks_len: ${actor_rollout_ref.model.action_chunks_len}
    use_proprio: ${actor_rollout_ref.rollout.use_proprio}
    strategy: fsdp  # This is for backward-compatibility
    traj_mini_batch_size: 16
    ppo_mini_batch_size: 256
    ppo_micro_batch_size: 64
    use_dynamic_bsz: False
    use_remove_padding: ${actor_rollout_ref.model.use_remove_padding}
    ppo_max_token_len_per_gpu: 20480 # n * ${data.max_prompt_length} + ${data.max_response_length}
    grad_clip: 1.0
    clip_ratio_high: 0.28
    clip_ratio_low: 0.2
    entropy_coeff: 0.001
    ppo_epochs: 1
    shuffle: True
    ulysses_sequence_parallel_size: 1 # sp size
    num_images_in_input: 1
    optim:
      lr: 1e-6
      lr_warmup_steps_ratio: 0.  # the total steps will be injected during runtime
      min_lr_ratio: null   # only useful for warmup with cosine
      warmup_style: constant  # select from constant/cosine
      total_training_steps: -1  # must be override by program
    fsdp_config:
      wrap_policy:
        # transformer_layer_cls_to_wrap: None
        min_num_params: 0
      param_offload: False
      grad_offload: False
      optimizer_offload: False
      fsdp_size: -1
  ref:
    fsdp_config:
      param_offload: False
      wrap_policy:
        # transformer_layer_cls_to_wrap: None
        min_num_params: 0
      fsdp_size: -1
    log_prob_micro_batch_size: 128
    log_prob_use_dynamic_bsz: ${actor_rollout_ref.actor.use_dynamic_bsz}
    log_prob_max_token_len_per_gpu: ${actor_rollout_ref.actor.ppo_max_token_len_per_gpu}
    ulysses_sequence_parallel_size: ${actor_rollout_ref.actor.ulysses_sequence_parallel_size} # sp size
  rollout:
    vla: ${actor_rollout_ref.model.vla}
    action_chunks_len: ${actor_rollout_ref.model.action_chunks_len}
    experiment_name: None
    unnorm_key: libero_10
    twin2_task_config: demo_randomized
    twin2_ckpt_setting: ${actor_rollout_ref.rollout.twin2_task_config}
    twin2_instruction_type: unseen
    micro_batch_size: 1
    val_micro_batch_size: 8
    model_family: openvla
    task_suite_name: libero_10
    num_steps_wait: 10
    use_proprio: False
    pretrained_checkpoint: None
    center_crop: True
    max_prompt_length: 512
    num_images_in_input: 1
    world_model:
      checkpoint: null
      use_pixel_rope: False
      default_cfg: 3.0
    name: vllm
    temperature: 1.0
    top_k: -1 # 0 for hf rollout, -1 for vllm rollout
    top_p: 1
    prompt_length: ${data.max_prompt_length}  # not use for opensource
    response_length: ${data.max_response_length}
    # for vllm rollout
    dtype: bfloat16 # should align with FSDP
    gpu_memory_utilization: 0.5
    ignore_eos: False
    enforce_eager: True
    free_cache_engine: True
    load_format: dummy_dtensor
    tensor_model_parallel_size: 2
    max_num_batched_tokens: 8192
    max_num_seqs: 1024
    log_prob_micro_batch_size: 128
    log_prob_use_dynamic_bsz: ${actor_rollout_ref.actor.use_dynamic_bsz}
    log_prob_max_token_len_per_gpu: ${actor_rollout_ref.actor.ppo_max_token_len_per_gpu}
    # for hf rollout
    do_sample: True
    # number of responses (i.e. num sample times)
    n: 1 # > 1 for grpo

critic:
  strategy: fsdp
  optim:
    lr: 1e-5
    lr_warmup_steps_ratio: 0.  # the total steps will be injected during runtime
    min_lr_ratio: null   # only useful for warmup with cosine
    warmup_style: constant  # select from constant/cosine
    total_training_steps: -1  # must be override by program
  model:
    action_token_len: ${actor_rollout_ref.model.action_token_len}
    action_chunks_len: ${actor_rollout_ref.model.action_chunks_len}
    path: ~/models/deepseek-llm-7b-chat
    tokenizer_path: ${actor_rollout_ref.model.path}
    override_config: { }
    external_lib: ${actor_rollout_ref.model.external_lib}
    use_remove_padding: ${actor_rollout_ref.model.use_remove_padding}
    enable_gradient_checkpointing: ${actor_rollout_ref.model.enable_gradient_checkpointing}
    fsdp_config:
      param_offload: ${actor_rollout_ref.actor.fsdp_config.param_offload}
      grad_offload: ${actor_rollout_ref.actor.fsdp_config.grad_offload}
      optimizer_offload: ${actor_rollout_ref.actor.fsdp_config.optimizer_offload}
      wrap_policy:
        # transformer_layer_cls_to_wrap: None
        min_num_params: 0
      fsdp_size: -1
    lora_rank: 0  # Set to positive value to enable LoRA (e.g., 32)
    lora_alpha: 32  # LoRA scaling factor
    target_modules: all-linear 
    type: value # if set to implicit, this will become an implicit PRM which updates according to gt. this only supports initializing from the reference model currently.
  ppo_mini_batch_size: ${actor_rollout_ref.actor.ppo_mini_batch_size}
  ppo_micro_batch_size: 64
  forward_micro_batch_size: ${critic.ppo_micro_batch_size}
  use_dynamic_bsz: ${actor_rollout_ref.actor.use_dynamic_bsz}
  ppo_max_token_len_per_gpu: 32768 # (${actor_rollout_ref.actor.ppo_max_token_len_per_gpu}) * 2
  forward_max_token_len_per_gpu: ${critic.ppo_max_token_len_per_gpu}
  ulysses_sequence_parallel_size: ${actor_rollout_ref.actor.ulysses_sequence_parallel_size} # sp size
  ppo_epochs: ${actor_rollout_ref.actor.ppo_epochs}
  shuffle: ${actor_rollout_ref.actor.shuffle}
  grad_clip: 1.0
  cliprange_value: 0.5

# verifier is more than source of reward. so it should be independent
verifier:
  type: prime
#  timeout: 5
#  num_processes: 64
  reward_coef: 5

reward_model:
  enable: True
  strategy: fsdp
  model:
    action_token_len: ${actor_rollout_ref.model.action_token_len}
    action_chunks_len: ${actor_rollout_ref.model.action_chunks_len}
    input_tokenizer: ${actor_rollout_ref.model.path}  # set this to null if the chat template is identical
    path: ~/models/FsfairX-LLaMA3-RM-v0.1
    external_lib: ${actor_rollout_ref.model.external_lib}
    use_remove_padding:  ${actor_rollout_ref.model.use_remove_padding}
    fsdp_config:
      min_num_params: 0
      param_offload: False
  mini_batch_size: ${actor_rollout_ref.actor.ppo_mini_batch_size}
  micro_batch_size: 64
  max_length: null
  ulysses_sequence_parallel_size: ${actor_rollout_ref.actor.ulysses_sequence_parallel_size} # sp size
  use_dynamic_bsz: ${critic.use_dynamic_bsz}
  ppo_max_token_len_per_gpu: ${actor_rollout_ref.actor.ppo_max_token_len_per_gpu}
  forward_max_token_len_per_gpu: ${critic.forward_max_token_len_per_gpu}
  rm_coef: 0 # weight for the reward model
  rm_type: prime # set to prime for process reward
  # configurations for process rewards of prime
  prime_granularity: token # whole
  prime_norm: batch_norm # batch_norm or none. if set to none, the normalizer is beta_train
  prime_model:
    input_tokenizer: ${actor_rollout_ref.model.path}
    path: /home/wangzefan/huggingface/dpo-prm
    ref_type: freeze # policy
    ref_path: /data/public/wangshuo/LongContext/model/meta-llama/Llama3.1-8b-instruct
    external_lib: ${actor_rollout_ref.model.external_lib}
    enable_gradient_checkpointing: ${actor_rollout_ref.model.enable_gradient_checkpointing}
    use_remove_padding:  ${actor_rollout_ref.model.use_remove_padding}
    fsdp_config:
      wrap_policy:
        min_num_params: 0
      param_offload: ${actor_rollout_ref.actor.fsdp_config.param_offload}
      grad_offload: ${actor_rollout_ref.actor.fsdp_config.grad_offload}
      optimizer_offload: ${actor_rollout_ref.actor.fsdp_config.optimizer_offload}
    update: none #before, after, or none
    optim:
      lr: 1e-6
      lr_warmup_steps_ratio: 0.
      min_lr_ratio: null
      warmup_style: constant
      total_training_steps: -1  # must be override by program
      weight_decay: 0.
      grad_clip: 1.0
    beta_train: 0.05
    loss_type: ce # currently only supports ce loss



algorithm:
  gamma: 1.0
  lam: 1.0
  adv_estimator: gae
  # now supports rloo. it treats different source of reward separately.
  # TODO: it should also support different gamma for different rewards.
  adv_params:
    verifier_gamma: ${algorithm.gamma}
    reward_model_gamma: ${algorithm.gamma}
  kl_penalty: kl  # how to estimate kl divergence
  kl_ctrl:
    type: fixed
    kl_coef: 0.001

trainer:
  total_epochs: 30
  total_training_steps: null
  project_name: verl_examples
  experiment_name: gsm8k
  logger: ['console', 'wandb']
  wandb_mode: online
  nnodes: 1
  n_gpus_per_node: 8
  save_freq: -1
  test_freq: -1
  critic_warmup: 0
  default_hdfs_dir: ~/experiments/gsm8k/ppo/${trainer.experiment_name}
  default_local_dir: checkpoints/${trainer.project_name}/${trainer.experiment_name}
  runtime_env: none
  val_before_train: False
  val_only: True
